//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_UTILS MkDir		${SYSDRIVE}\graphics\
RUN_UTILS MkDir		${SYSDRIVE}\graphics\wserv\

RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-PublicApi.script			${SYSDRIVE}\graphics\GRAPHICS-WSERV-PublicApi.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-PublicApi.script

RUN_UTILS CopyFile	z:\graphics\t_graphics.tcs							${SYSDRIVE}\graphics\t_graphics.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\t_graphics.tcs
RUN_UTILS CopyFile	z:\graphics\t_graphics_panic.tcs					${SYSDRIVE}\graphics\t_graphics_panic.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\t_graphics_panic.tcs


//T_DataWsSession
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-Session-PublicApi.script		${SYSDRIVE}\graphics\GRAPHICS-WSERV-Session-PublicApi.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-Session-PublicApi.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-Session-PublicApi.ini		${SYSDRIVE}\graphics\GRAPHICS-WSERV-Session-PublicApi.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-Session-PublicApi.ini

//T_DataWindowGroup
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WindowGroup-PublicApi.script		${SYSDRIVE}\graphics\GRAPHICS-WSERV-WindowGroup-PublicApi.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-WindowGroup-PublicApi.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WindowGroup-PublicApi.ini		${SYSDRIVE}\graphics\GRAPHICS-WSERV-WindowGroup-PublicApi.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-WindowGroup-PublicApi.ini

//T_DataBlankWindow
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-BlankWindow-PublicApi.script		${SYSDRIVE}\graphics\GRAPHICS-WSERV-BlankWindow-PublicApi.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-BlankWindow-PublicApi.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-BlankWindow-PublicApi.ini		${SYSDRIVE}\graphics\GRAPHICS-WSERV-BlankWindow-PublicApi.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-BlankWindow-PublicApi.ini

//T_DataWindow
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-Window-PublicApi.script		${SYSDRIVE}\graphics\GRAPHICS-WSERV-Window-PublicApi.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-Window-PublicApi.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-Window-PublicApi.ini			${SYSDRIVE}\graphics\GRAPHICS-WSERV-Window-PublicApi.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-Window-PublicApi.ini

//T_DataBackedUpWindow
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-BackedUpWindow-PublicApi.script	${SYSDRIVE}\graphics\GRAPHICS-WSERV-BackedUpWindow-PublicApi.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-BackedUpWindow-PublicApi.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-BackedUpWindow-PublicApi.ini		${SYSDRIVE}\graphics\GRAPHICS-WSERV-BackedUpWindow-PublicApi.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-BackedUpWindow-PublicApi.ini

//T_DataWindowGc
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WindowGc-PublicApi.script		${SYSDRIVE}\graphics\GRAPHICS-WSERV-WindowGc-PublicApi.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-WindowGc-PublicApi.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WindowGc-PublicApi.ini		${SYSDRIVE}\graphics\GRAPHICS-WSERV-WindowGc-PublicApi.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-WindowGc-PublicApi.ini

//T_DataWsBitmap
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WsBitmap-PublicApi.script		${SYSDRIVE}\graphics\GRAPHICS-WSERV-WsBitmap-PublicApi.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-WsBitmap-PublicApi.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WsBitmap-PublicApi.ini		${SYSDRIVE}\graphics\GRAPHICS-WSERV-WsBitmap-PublicApi.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-WsBitmap-PublicApi.ini

//T_DataGraphicBitmap
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WsGraphicBitmap-PublicApi.script	${SYSDRIVE}\graphics\GRAPHICS-WSERV-WsGraphicBitmap-PublicApi.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-WsGraphicBitmap-PublicApi.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WsGraphicBitmap-PublicApi.ini	${SYSDRIVE}\graphics\GRAPHICS-WSERV-WsGraphicBitmap-PublicApi.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-WsGraphicBitmap-PublicApi.ini

//T_DataGraphicMsgBuf
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WsGraphicMsgBuf-PublicApi.script	${SYSDRIVE}\graphics\GRAPHICS-WSERV-WsGraphicMsgBuf-PublicApi.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-WsGraphicMsgBuf-PublicApi.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WsGraphicMsgBuf-PublicApi.ini	${SYSDRIVE}\graphics\GRAPHICS-WSERV-WsGraphicMsgBuf-PublicApi.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-WsGraphicMsgBuf-PublicApi.ini

//T_DataWsEvent T_DataWsPriorityKeyEvent T_DataWsRedrawEvent
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-Events-PublicApi.script		${SYSDRIVE}\graphics\GRAPHICS-WSERV-Events-PublicApi.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-Events-PublicApi.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-Events-PublicApi.ini			${SYSDRIVE}\graphics\GRAPHICS-WSERV-Events-PublicApi.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-WSERV-Events-PublicApi.ini

//T_DataDirectScreenAccess
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-DirectScreenAccess-PublicApi.script		c:\graphics\GRAPHICS-WSERV-DirectScreenAccess-PublicApi.script
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-DirectScreenAccess-PublicApi.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-DirectScreenAccess-PublicApi.ini			c:\graphics\GRAPHICS-WSERV-DirectScreenAccess-PublicApi.ini
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-DirectScreenAccess-PublicApi.ini

//T_DataDsaSession
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-DsaSession-PublicApi.script		c:\graphics\GRAPHICS-WSERV-DsaSession-PublicApi.script
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-DsaSession-PublicApi.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-DsaSession-PublicApi.ini			c:\graphics\GRAPHICS-WSERV-DsaSession-PublicApi.ini
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-DsaSession-PublicApi.ini

//T_DataWsSprite
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WsSprite-PublicApi.script		c:\graphics\GRAPHICS-WSERV-WsSprite-PublicApi.script
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-WsSprite-PublicApi.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WsSprite-PublicApi.ini			c:\graphics\GRAPHICS-WSERV-WsSprite-PublicApi.ini
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-WsSprite-PublicApi.ini

//T_DataWsPointerCursor
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WsPointerCursor-PublicApi.script		c:\graphics\GRAPHICS-WSERV-WsPointerCursor-PublicApi.script
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-WsPointerCursor-PublicApi.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WsPointerCursor-PublicApi.ini			c:\graphics\GRAPHICS-WSERV-WsPointerCursor-PublicApi.ini
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-WsPointerCursor-PublicApi.ini

//T_DataSoundPlugIn
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-SoundPlugin-PublicAPI.script		c:\graphics\GRAPHICS-WSERV-SoundPlugin-PublicAPI.script
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-SoundPlugin-PublicAPI.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-SoundPlugin-PublicAPI.ini		c:\graphics\GRAPHICS-WSERV-SoundPlugin-PublicAPI.ini
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-SoundPlugin-PublicAPI.ini

//T_DataWSScreenDevice
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WsScreenDevice-PublicAPI.script		c:\graphics\GRAPHICS-WSERV-WsScreenDevice-PublicAPI.script
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-WsScreenDevice-PublicAPI.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WsScreenDevice-PublicAPI.ini		c:\graphics\GRAPHICS-WSERV-WsScreenDevice-PublicAPI.ini
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-WsScreenDevice-PublicAPI.ini

//T_DataFrame
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-Frame-PublicAPI.script		c:\graphics\GRAPHICS-WSERV-Frame-PublicAPI.script
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-Frame-PublicAPI.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-Frame-PublicAPI.ini		c:\graphics\GRAPHICS-WSERV-Frame-PublicAPI.ini
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-Frame-PublicAPI.ini

//T_DataWsGraphicBitmapAnimation
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WsGraphicBitmapAnimation-PublicAPI.script		c:\graphics\GRAPHICS-WSERV-WsGraphicBitmapAnimation-PublicAPI.script
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-WsGraphicBitmapAnimation-PublicAPI.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-WsGraphicBitmapAnimation-PublicAPI.ini		c:\graphics\GRAPHICS-WSERV-WsGraphicBitmapAnimation-PublicAPI.ini
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-WsGraphicBitmapAnimation-PublicAPI.ini

//T_DataAnim
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-Anim-PublicAPI.script		c:\graphics\GRAPHICS-WSERV-Anim-PublicAPI.script
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-Anim-PublicAPI.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-Anim-PublicAPI.ini		c:\graphics\GRAPHICS-WSERV-Anim-PublicAPI.ini
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-Anim-PublicAPI.ini

//T_DataAnimDll
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-AnimDll-PublicAPI.script		c:\graphics\GRAPHICS-WSERV-AnimDll-PublicAPI.script
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-AnimDll-PublicAPI.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-AnimDll-PublicAPI.ini		c:\graphics\GRAPHICS-WSERV-AnimDll-PublicAPI.ini
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-AnimDll-PublicAPI.ini

//T_DataAnimForMClass
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-AnimGfwe-PublicAPI.script		c:\graphics\GRAPHICS-WSERV-AnimGfwe-PublicAPI.script
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-AnimGfwe-PublicAPI.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-AnimGfwe-PublicAPI.ini		c:\graphics\GRAPHICS-WSERV-AnimGfwe-PublicAPI.ini
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-AnimGfwe-PublicAPI.ini

RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-AnimWindowFunctions-PublicAPI.script		c:\graphics\GRAPHICS-WSERV-AnimWindowFunctions-PublicAPI.script
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-AnimWindowFunctions-PublicAPI.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-AnimWindowFunctions-PublicAPI.ini		c:\graphics\GRAPHICS-WSERV-AnimWindowFunctions-PublicAPI.ini
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-AnimWindowFunctions-PublicAPI.ini

RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-AnimGeneralFunctions-PublicAPI.script		c:\graphics\GRAPHICS-WSERV-AnimGeneralFunctions-PublicAPI.script
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-AnimGeneralFunctions-PublicAPI.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-AnimGeneralFunctions-PublicAPI.ini		c:\graphics\GRAPHICS-WSERV-AnimGeneralFunctions-PublicAPI.ini
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-AnimGeneralFunctions-PublicAPI.ini

RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-AnimSpriteFunctions-PublicAPI.script		c:\graphics\GRAPHICS-WSERV-AnimSpriteFunctions-PublicAPI.script
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-AnimSpriteFunctions-PublicAPI.script
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-WSERV-AnimSpriteFunctions-PublicAPI.ini		c:\graphics\GRAPHICS-WSERV-AnimSpriteFunctions-PublicAPI.ini
RUN_UTILS MakeReadWrite	c:\graphics\GRAPHICS-WSERV-AnimSpriteFunctions-PublicAPI.ini


RUN_UTILS MkDir		\graphics\wserv

//datafile test_board.mbm
RUN_UTILS CopyFile	z:\graphics\wserv\test_board.mbm				${SYSDRIVE}\graphics\wserv\test_board.mbm
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\wserv\test_board.mbm

//datafile test_mask.mbm
RUN_UTILS CopyFile	z:\graphics\wserv\test_mask.mbm					${SYSDRIVE}\graphics\wserv\test_mask.mbm
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\wserv\test_mask.mbm

//datafile test_alpha.mbm
RUN_UTILS CopyFile	z:\graphics\wserv\test_alpha.mbm				${SYSDRIVE}\graphics\wserv\test_alpha.mbm
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\wserv\test_alpha.mbm
//datafile test_rwssprite_bitmap.mbm
RUN_UTILS CopyFile	z:\graphics\wserv\test_rwssprite_bitmap.mbm			${SYSDRIVE}\graphics\wserv\test_rwssprite_bitmap.mbm
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\wserv\test_rwssprite_bitmap.mbm

//datafile WsGraphicBitmapAnimation.mbm
RUN_UTILS CopyFile	z:\graphics\wserv\WsGraphicBitmapAnimation.mbm		${SYSDRIVE}\graphics\wserv\WsGraphicBitmapAnimation.mbm
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\wserv\WsGraphicBitmapAnimation.mbm

//datafile testfontws.gdr
RUN_UTILS CopyFile	z:\graphics\wserv\testfontws.gdr		${SYSDRIVE}\graphics\wserv\testfontws.gdr
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\wserv\testfontws.gdr
